// Copyright 2020 Intel Corporation
// SPDX-License-Identifier: MIT

// Generated by one of Gregg's toys.   Share And Enjoy.
// Executable compiled Sep 14 2017 14:08:19
// This file was generated 08/05/2020 12:32:55

// This is a small one.  building it from simple LUTs

//   output is offset +72
module prio_enc_w6_t2_b72 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [5:0] din,
    output [6:0] dout
);

wire [6:0] dout_w;

////////////////////////////////
// all inputs -> output[0]


generate
    if (SIM_EMULATE) begin
        wire [63:0] local_mask = 64'h4544454545444545;
        wire [5:0] local_din = {din[5],din[4],din[3],din[2],din[1],din[0]};
        assign dout_w[0] = local_mask [local_din];
    end else begin
        //Note: the S5 cell is 99% the same, and compatible
        //stratixv_lcell_comb s5c (
 
        tennm_lcell_comb  #(
            .lut_mask(64'h4544454545444545),
            .shared_arith("off"),
            .extended_lut("off")
        ) s10c_0 (
            .dataa (din[0]),
            .datab (din[1]),
            .datac (din[2]),
            .datad (din[3]),
            .datae (din[4]),
            .dataf (din[5]),
            .datag(1'b1),
            
            .cin(1'b1),
            
            
            // synthesis translate_off
            // this is for stratix 10 (fourteen) but not the others
            .datah(1'b1),
                        
            // this does not exist in S10, but is partially there in the models right this second
            .sharein(1'b0),
            // synthesis translate_on
            
            .sumout(),.cout(),.shareout(),
            .combout(dout_w[0])
        );
    end
endgenerate

////////////////////////////////
// all inputs -> output[1]


generate
    if (SIM_EMULATE) begin
        wire [63:0] local_mask = 64'h1110111011101111;
        wire [5:0] local_din = {din[5],din[4],din[3],din[2],din[1],din[0]};
        assign dout_w[1] = local_mask [local_din];
    end else begin
        //Note: the S5 cell is 99% the same, and compatible
        //stratixv_lcell_comb s5c (
 
        tennm_lcell_comb  #(
            .lut_mask(64'h1110111011101111),
            .shared_arith("off"),
            .extended_lut("off")
        ) s10c_1 (
            .dataa (din[0]),
            .datab (din[1]),
            .datac (din[2]),
            .datad (din[3]),
            .datae (din[4]),
            .dataf (din[5]),
            .datag(1'b1),
            
            .cin(1'b1),
            
            
            // synthesis translate_off
            // this is for stratix 10 (fourteen) but not the others
            .datah(1'b1),
                        
            // this does not exist in S10, but is partially there in the models right this second
            .sharein(1'b0),
            // synthesis translate_on
            
            .sumout(),.cout(),.shareout(),
            .combout(dout_w[1])
        );
    end
endgenerate

////////////////////////////////
// all inputs -> output[2]


generate
    if (SIM_EMULATE) begin
        wire [63:0] local_mask = 64'h0001000100010001;
        wire [5:0] local_din = {din[5],din[4],din[3],din[2],din[1],din[0]};
        assign dout_w[2] = local_mask [local_din];
    end else begin
        //Note: the S5 cell is 99% the same, and compatible
        //stratixv_lcell_comb s5c (
 
        tennm_lcell_comb  #(
            .lut_mask(64'h0001000100010001),
            .shared_arith("off"),
            .extended_lut("off")
        ) s10c_2 (
            .dataa (din[0]),
            .datab (din[1]),
            .datac (din[2]),
            .datad (din[3]),
            .datae (din[4]),
            .dataf (din[5]),
            .datag(1'b1),
            
            .cin(1'b1),
            
            
            // synthesis translate_off
            // this is for stratix 10 (fourteen) but not the others
            .datah(1'b1),
                        
            // this does not exist in S10, but is partially there in the models right this second
            .sharein(1'b0),
            // synthesis translate_on
            
            .sumout(),.cout(),.shareout(),
            .combout(dout_w[2])
        );
    end
endgenerate

////////////////////////////////
// all inputs -> output[3]


generate
    if (SIM_EMULATE) begin
        wire [63:0] local_mask = 64'hffffffffffffffff;
        wire [5:0] local_din = {din[5],din[4],din[3],din[2],din[1],din[0]};
        assign dout_w[3] = local_mask [local_din];
    end else begin
        //Note: the S5 cell is 99% the same, and compatible
        //stratixv_lcell_comb s5c (
 
        tennm_lcell_comb  #(
            .lut_mask(64'hffffffffffffffff),
            .shared_arith("off"),
            .extended_lut("off")
        ) s10c_3 (
            .dataa (din[0]),
            .datab (din[1]),
            .datac (din[2]),
            .datad (din[3]),
            .datae (din[4]),
            .dataf (din[5]),
            .datag(1'b1),
            
            .cin(1'b1),
            
            
            // synthesis translate_off
            // this is for stratix 10 (fourteen) but not the others
            .datah(1'b1),
                        
            // this does not exist in S10, but is partially there in the models right this second
            .sharein(1'b0),
            // synthesis translate_on
            
            .sumout(),.cout(),.shareout(),
            .combout(dout_w[3])
        );
    end
endgenerate

////////////////////////////////
// all inputs -> output[4]


generate
    if (SIM_EMULATE) begin
        wire [63:0] local_mask = 64'h0000000000000001;
        wire [5:0] local_din = {din[5],din[4],din[3],din[2],din[1],din[0]};
        assign dout_w[4] = local_mask [local_din];
    end else begin
        //Note: the S5 cell is 99% the same, and compatible
        //stratixv_lcell_comb s5c (
 
        tennm_lcell_comb  #(
            .lut_mask(64'h0000000000000001),
            .shared_arith("off"),
            .extended_lut("off")
        ) s10c_4 (
            .dataa (din[0]),
            .datab (din[1]),
            .datac (din[2]),
            .datad (din[3]),
            .datae (din[4]),
            .dataf (din[5]),
            .datag(1'b1),
            
            .cin(1'b1),
            
            
            // synthesis translate_off
            // this is for stratix 10 (fourteen) but not the others
            .datah(1'b1),
                        
            // this does not exist in S10, but is partially there in the models right this second
            .sharein(1'b0),
            // synthesis translate_on
            
            .sumout(),.cout(),.shareout(),
            .combout(dout_w[4])
        );
    end
endgenerate

////////////////////////////////
// all inputs -> output[5]


generate
    if (SIM_EMULATE) begin
        wire [63:0] local_mask = 64'h0000000000000001;
        wire [5:0] local_din = {din[5],din[4],din[3],din[2],din[1],din[0]};
        assign dout_w[5] = local_mask [local_din];
    end else begin
        //Note: the S5 cell is 99% the same, and compatible
        //stratixv_lcell_comb s5c (
 
        tennm_lcell_comb  #(
            .lut_mask(64'h0000000000000001),
            .shared_arith("off"),
            .extended_lut("off")
        ) s10c_5 (
            .dataa (din[0]),
            .datab (din[1]),
            .datac (din[2]),
            .datad (din[3]),
            .datae (din[4]),
            .dataf (din[5]),
            .datag(1'b1),
            
            .cin(1'b1),
            
            
            // synthesis translate_off
            // this is for stratix 10 (fourteen) but not the others
            .datah(1'b1),
                        
            // this does not exist in S10, but is partially there in the models right this second
            .sharein(1'b0),
            // synthesis translate_on
            
            .sumout(),.cout(),.shareout(),
            .combout(dout_w[5])
        );
    end
endgenerate

////////////////////////////////
// all inputs -> output[6]


generate
    if (SIM_EMULATE) begin
        wire [63:0] local_mask = 64'hffffffffffffffff;
        wire [5:0] local_din = {din[5],din[4],din[3],din[2],din[1],din[0]};
        assign dout_w[6] = local_mask [local_din];
    end else begin
        //Note: the S5 cell is 99% the same, and compatible
        //stratixv_lcell_comb s5c (
 
        tennm_lcell_comb  #(
            .lut_mask(64'hffffffffffffffff),
            .shared_arith("off"),
            .extended_lut("off")
        ) s10c_6 (
            .dataa (din[0]),
            .datab (din[1]),
            .datac (din[2]),
            .datad (din[3]),
            .datae (din[4]),
            .dataf (din[5]),
            .datag(1'b1),
            
            .cin(1'b1),
            
            
            // synthesis translate_off
            // this is for stratix 10 (fourteen) but not the others
            .datah(1'b1),
                        
            // this does not exist in S10, but is partially there in the models right this second
            .sharein(1'b0),
            // synthesis translate_on
            
            .sumout(),.cout(),.shareout(),
            .combout(dout_w[6])
        );
    end
endgenerate

////////////////////////////////
// output latency is 2

reg [2*7-1:0] dout_r;
always @(posedge clk) dout_r <= {dout_r[6:0],dout_w};
assign dout = dout_r[13:7];

endmodule

