# TCL File Generated by Component Editor 22.2
# Thu Mar 17 15:20:27 PDT 2022
# DO NOT MODIFY


# 
# st2mm "st2mm" v1.0
#  2022.03.17.15:20:27
# 
# 

# 
# request TCL package from ACDS 22.1
# 
package require -exact qsys 22.1


# 
# module st2mm
# 
set_module_property DESCRIPTION ""
set_module_property NAME st2mm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ofs infra"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME st2mm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL st2mm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi_lite_if_conn.sv SYSTEM_VERILOG PATH axi_lite_if_conn.sv
add_fileset_file axis_demux.sv SYSTEM_VERILOG PATH ../../../../fims/n6000/afu/pf_vf_mux_top/axis_demux.sv
add_fileset_file fake_responder.sv SYSTEM_VERILOG PATH fake_responder.sv
add_fileset_file mctp_rx_bridge.sv SYSTEM_VERILOG PATH mctp_rx_bridge.sv
add_fileset_file mctp_tx_bridge.sv SYSTEM_VERILOG PATH mctp_tx_bridge.sv
add_fileset_file mmio_req_bridge.sv SYSTEM_VERILOG PATH mmio_req_bridge.sv
add_fileset_file mmio_rsp_arbiter.sv SYSTEM_VERILOG PATH mmio_rsp_arbiter.sv
add_fileset_file mmio_rsp_bridge.sv SYSTEM_VERILOG PATH mmio_rsp_bridge.sv
add_fileset_file mmio_rsp_tag_tracker.sv SYSTEM_VERILOG PATH mmio_rsp_tag_tracker.sv
add_fileset_file pcie_axis_cdc_fifo.sv SYSTEM_VERILOG PATH pcie_axis_cdc_fifo.sv
add_fileset_file pcie_axis_mux.sv SYSTEM_VERILOG PATH pcie_axis_mux.sv
add_fileset_file st2mm.sv SYSTEM_VERILOG PATH st2mm.sv TOP_LEVEL_FILE
add_fileset_file st2mm_csr.sv SYSTEM_VERILOG PATH st2mm_csr.sv
add_fileset_file st2mm_packet_filter.sv SYSTEM_VERILOG PATH st2mm_packet_filter.sv
add_fileset_file st2mm_pkg.sv SYSTEM_VERILOG PATH st2mm_pkg.sv
add_fileset_file st2mm_rx_bridge.sv SYSTEM_VERILOG PATH st2mm_rx_bridge.sv
add_fileset_file st2mm_tx_bridge.sv SYSTEM_VERILOG PATH st2mm_tx_bridge.sv
add_fileset_file fabric_pkg.sv SYSTEM_VERILOG PATH ../../../../pd_qsys/n6000/fabric/fabric_pkg.sv
add_fileset_file fpga_defines.vh OTHER PATH ../../../../fims/n6000/includes/fpga_defines.vh
add_fileset_file ofs_axis_if.sv SYSTEM_VERILOG PATH ../../../../includes/ofs_axis_if.sv
#add_fileset_file ofs_csr_pkg.sv SYSTEM_VERILOG PATH ../../../../includes/ofs_csr_pkg.sv
#add_fileset_file ofs_fim_axi_lite_if.sv SYSTEM_VERILOG PATH ../../../../includes/ofs_fim_axi_lite_if.sv SYSTEMVERILOG_INTERFACE
#add_fileset_file pcie_ss_axis_if.sv SYSTEM_VERILOG PATH ../../../../includes/pcie_ss_axis_if.sv SYSTEMVERILOG_INTERFACE
#add_fileset_file ofs_fim_cfg_pkg.sv SYSTEM_VERILOG PATH ../../../../fims/n6000/includes/ofs_fim_cfg_pkg.sv
#add_fileset_file ofs_fim_if_pkg.sv SYSTEM_VERILOG PATH ../../../../includes/ofs_fim_if_pkg.sv
add_fileset_file ofs_pcie_ss_cfg.vh OTHER PATH ../../../../includes/ofs_pcie_ss_cfg.vh
#add_fileset_file ofs_pcie_ss_cfg_pkg.sv SYSTEM_VERILOG PATH ../../../../includes/ofs_pcie_ss_cfg_pkg.sv
add_fileset_file ofs_pcie_ss_plat_cfg.vh OTHER PATH ../../../../fims/n6000/includes/ofs_pcie_ss_plat_cfg.vh
#add_fileset_file ofs_pcie_ss_plat_cfg_pkg.sv SYSTEM_VERILOG PATH ../../../../fims/n6000/includes/ofs_pcie_ss_plat_cfg_pkg.sv
#add_fileset_file pcie_ss_axis_pkg.sv SYSTEM_VERILOG PATH ../../../../includes/pcie_ss_axis_pkg.sv
add_fileset_file pcie_ss_hdr_pkg.sv SYSTEM_VERILOG PATH ../../../../includes/pcie_ss_hdr_pkg.sv
#add_fileset_file pcie_ss_pkg.sv SYSTEM_VERILOG PATH ../../../../includes/pcie_ss_pkg.sv
add_fileset_file vendor_defines.vh OTHER PATH ../../../../includes/vendor_defines.vh
add_fileset_file altera_std_synchronizer_nocut.v VERILOG PATH ../../../../common/sync/altera_std_synchronizer_nocut.v
add_fileset_file axi_lite2mmio.sv SYSTEM_VERILOG PATH ../../../../common/axi_lite2mmio.sv
add_fileset_file axis_mux.sv SYSTEM_VERILOG PATH ../../../../fims/n6000/afu/pf_vf_mux_top/axis_mux.sv
add_fileset_file axis_register.sv SYSTEM_VERILOG PATH ../../../../common/axis/axis_register.sv
add_fileset_file axis_tx_msix_bridge.sv SYSTEM_VERILOG PATH ../../../../common/axis_tx_msix_bridge.sv
add_fileset_file fair_arbiter.sv SYSTEM_VERILOG PATH ../../../../common/arbiter/fair_arbiter.sv
add_fileset_file fim_dcfifo.sdc SDC PATH ../../../../common/fifo/fim_dcfifo.sdc
add_fileset_file fim_dcfifo.sv SYSTEM_VERILOG PATH ../../../../common/fifo/fim_dcfifo.sv
add_fileset_file fim_rdack_dcfifo.sv SYSTEM_VERILOG PATH ../../../../common/fifo/fim_rdack_dcfifo.sv
add_fileset_file fim_rdack_scfifo.sv SYSTEM_VERILOG PATH ../../../../common/fifo/fim_rdack_scfifo.sv
add_fileset_file fim_resync.sv SYSTEM_VERILOG PATH ../../../../common/sync/fim_resync.sv
add_fileset_file fim_scfifo.sv SYSTEM_VERILOG PATH ../../../../common/fifo/fim_scfifo.sv
add_fileset_file ofs_fim_axi_csr_slave.sv SYSTEM_VERILOG PATH ../../../../common/ofs_fim_axi_csr_slave.sv
add_fileset_file ofs_fim_axi_mmio_if.sv SYSTEM_VERILOG PATH ../../../../includes/ofs_fim_axi_mmio_if.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL st2mm
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi_lite_if_conn.sv SYSTEM_VERILOG PATH axi_lite_if_conn.sv
add_fileset_file axis_demux.sv SYSTEM_VERILOG PATH ../../../../fims/n6000/afu/pf_vf_mux_top/axis_demux.sv
add_fileset_file fake_responder.sv SYSTEM_VERILOG PATH fake_responder.sv
add_fileset_file mctp_rx_bridge.sv SYSTEM_VERILOG PATH mctp_rx_bridge.sv
add_fileset_file mctp_tx_bridge.sv SYSTEM_VERILOG PATH mctp_tx_bridge.sv
add_fileset_file mmio_req_bridge.sv SYSTEM_VERILOG PATH mmio_req_bridge.sv
add_fileset_file mmio_rsp_arbiter.sv SYSTEM_VERILOG PATH mmio_rsp_arbiter.sv
add_fileset_file mmio_rsp_bridge.sv SYSTEM_VERILOG PATH mmio_rsp_bridge.sv
add_fileset_file mmio_rsp_tag_tracker.sv SYSTEM_VERILOG PATH mmio_rsp_tag_tracker.sv
add_fileset_file pcie_axis_cdc_fifo.sv SYSTEM_VERILOG PATH pcie_axis_cdc_fifo.sv
add_fileset_file pcie_axis_mux.sv SYSTEM_VERILOG PATH pcie_axis_mux.sv
add_fileset_file st2mm.sv SYSTEM_VERILOG PATH st2mm.sv TOP_LEVEL_FILE
add_fileset_file st2mm_csr.sv SYSTEM_VERILOG PATH st2mm_csr.sv
add_fileset_file st2mm_packet_filter.sv SYSTEM_VERILOG PATH st2mm_packet_filter.sv
add_fileset_file st2mm_pkg.sv SYSTEM_VERILOG PATH st2mm_pkg.sv
add_fileset_file st2mm_rx_bridge.sv SYSTEM_VERILOG PATH st2mm_rx_bridge.sv
add_fileset_file st2mm_tx_bridge.sv SYSTEM_VERILOG PATH st2mm_tx_bridge.sv
add_fileset_file fabric_pkg.sv SYSTEM_VERILOG PATH ../../../../pd_qsys/n6000/fabric/fabric_pkg.sv
add_fileset_file fpga_defines.vh OTHER PATH ../../../../fims/n6000/includes/fpga_defines.vh
add_fileset_file ofs_axis_if.sv SYSTEM_VERILOG PATH ../../../../includes/ofs_axis_if.sv
#add_fileset_file ofs_csr_pkg.sv SYSTEM_VERILOG PATH ../../../../includes/ofs_csr_pkg.sv
#add_fileset_file ofs_fim_axi_lite_if.sv SYSTEM_VERILOG PATH ../../../../includes/ofs_fim_axi_lite_if.sv SYSTEMVERILOG_INTERFACE
#add_fileset_file pcie_ss_axis_if.sv SYSTEM_VERILOG PATH ../../../../includes/pcie_ss_axis_if.sv SYSTEMVERILOG_INTERFACE
#add_fileset_file ofs_fim_cfg_pkg.sv SYSTEM_VERILOG PATH ../../../../fims/n6000/includes/ofs_fim_cfg_pkg.sv
#add_fileset_file ofs_fim_if_pkg.sv SYSTEM_VERILOG PATH ../../../../includes/ofs_fim_if_pkg.sv
add_fileset_file ofs_pcie_ss_cfg.vh OTHER PATH ../../../../includes/ofs_pcie_ss_cfg.vh
#add_fileset_file ofs_pcie_ss_cfg_pkg.sv SYSTEM_VERILOG PATH ../../../../includes/ofs_pcie_ss_cfg_pkg.sv
add_fileset_file ofs_pcie_ss_plat_cfg.vh OTHER PATH ../../../../fims/n6000/includes/ofs_pcie_ss_plat_cfg.vh
#add_fileset_file ofs_pcie_ss_plat_cfg_pkg.sv SYSTEM_VERILOG PATH ../../../../fims/n6000/includes/ofs_pcie_ss_plat_cfg_pkg.sv
#add_fileset_file pcie_ss_axis_pkg.sv SYSTEM_VERILOG PATH ../../../../includes/pcie_ss_axis_pkg.sv
#add_fileset_file pcie_ss_hdr_pkg.sv SYSTEM_VERILOG PATH ../../../../includes/pcie_ss_hdr_pkg.sv
#add_fileset_file pcie_ss_pkg.sv SYSTEM_VERILOG PATH ../../../../includes/pcie_ss_pkg.sv
add_fileset_file vendor_defines.vh OTHER PATH ../../../../includes/vendor_defines.vh
add_fileset_file altera_std_synchronizer_nocut.v VERILOG PATH ../../../../common/sync/altera_std_synchronizer_nocut.v
add_fileset_file axi_lite2mmio.sv SYSTEM_VERILOG PATH ../../../../common/axi_lite2mmio.sv
add_fileset_file axis_mux.sv SYSTEM_VERILOG PATH ../../../../fims/n6000/afu/pf_vf_mux_top/axis_mux.sv
add_fileset_file axis_register.sv SYSTEM_VERILOG PATH ../../../../common/axis/axis_register.sv
add_fileset_file axis_tx_msix_bridge.sv SYSTEM_VERILOG PATH ../../../../common/axis_tx_msix_bridge.sv
add_fileset_file fair_arbiter.sv SYSTEM_VERILOG PATH ../../../../common/arbiter/fair_arbiter.sv
add_fileset_file fim_dcfifo.sdc SDC PATH ../../../../common/fifo/fim_dcfifo.sdc
add_fileset_file fim_dcfifo.sv SYSTEM_VERILOG PATH ../../../../common/fifo/fim_dcfifo.sv
add_fileset_file fim_rdack_dcfifo.sv SYSTEM_VERILOG PATH ../../../../common/fifo/fim_rdack_dcfifo.sv
add_fileset_file fim_rdack_scfifo.sv SYSTEM_VERILOG PATH ../../../../common/fifo/fim_rdack_scfifo.sv
add_fileset_file fim_resync.sv SYSTEM_VERILOG PATH ../../../../common/sync/fim_resync.sv
add_fileset_file fim_scfifo.sv SYSTEM_VERILOG PATH ../../../../common/fifo/fim_scfifo.sv
add_fileset_file ofs_fim_axi_csr_slave.sv SYSTEM_VERILOG PATH ../../../../common/ofs_fim_axi_csr_slave.sv
add_fileset_file ofs_fim_axi_mmio_if.sv SYSTEM_VERILOG PATH ../../../../includes/ofs_fim_axi_mmio_if.sv


# 
# parameters
# 
add_parameter PF_NUM INTEGER 0
set_parameter_property PF_NUM DEFAULT_VALUE 0
set_parameter_property PF_NUM DISPLAY_NAME PF_NUM
set_parameter_property PF_NUM UNITS None
set_parameter_property PF_NUM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PF_NUM AFFECTS_GENERATION false
set_parameter_property PF_NUM HDL_PARAMETER true
set_parameter_property PF_NUM EXPORT true
add_parameter VF_NUM INTEGER 0
set_parameter_property VF_NUM DEFAULT_VALUE 0
set_parameter_property VF_NUM DISPLAY_NAME VF_NUM
set_parameter_property VF_NUM UNITS None
set_parameter_property VF_NUM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VF_NUM AFFECTS_GENERATION false
set_parameter_property VF_NUM HDL_PARAMETER true
set_parameter_property VF_NUM EXPORT true
add_parameter VF_ACTIVE INTEGER 0
set_parameter_property VF_ACTIVE DEFAULT_VALUE 0
set_parameter_property VF_ACTIVE DISPLAY_NAME VF_ACTIVE
set_parameter_property VF_ACTIVE UNITS None
set_parameter_property VF_ACTIVE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VF_ACTIVE AFFECTS_GENERATION false
set_parameter_property VF_ACTIVE HDL_PARAMETER true
set_parameter_property VF_ACTIVE EXPORT true
add_parameter MM_ADDR_WIDTH INTEGER 32
set_parameter_property MM_ADDR_WIDTH DEFAULT_VALUE 19
set_parameter_property MM_ADDR_WIDTH DISPLAY_NAME MM_ADDR_WIDTH
set_parameter_property MM_ADDR_WIDTH UNITS None
set_parameter_property MM_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MM_ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property MM_ADDR_WIDTH HDL_PARAMETER true
set_parameter_property MM_ADDR_WIDTH EXPORT true
add_parameter MM_DATA_WIDTH INTEGER 64
set_parameter_property MM_DATA_WIDTH DEFAULT_VALUE 64
set_parameter_property MM_DATA_WIDTH DISPLAY_NAME MM_DATA_WIDTH
set_parameter_property MM_DATA_WIDTH UNITS None
set_parameter_property MM_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MM_DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property MM_DATA_WIDTH HDL_PARAMETER true
set_parameter_property MM_DATA_WIDTH EXPORT true
add_parameter READ_ALLOWANCE INTEGER 1
set_parameter_property READ_ALLOWANCE DEFAULT_VALUE 1
set_parameter_property READ_ALLOWANCE DISPLAY_NAME READ_ALLOWANCE
set_parameter_property READ_ALLOWANCE UNITS None
set_parameter_property READ_ALLOWANCE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property READ_ALLOWANCE AFFECTS_GENERATION false
set_parameter_property READ_ALLOWANCE HDL_PARAMETER true
set_parameter_property READ_ALLOWANCE EXPORT true
add_parameter WRITE_ALLOWANCE INTEGER 1
set_parameter_property WRITE_ALLOWANCE DEFAULT_VALUE 64
set_parameter_property WRITE_ALLOWANCE DISPLAY_NAME WRITE_ALLOWANCE
set_parameter_property WRITE_ALLOWANCE UNITS None
set_parameter_property WRITE_ALLOWANCE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WRITE_ALLOWANCE AFFECTS_GENERATION false
set_parameter_property WRITE_ALLOWANCE HDL_PARAMETER true
set_parameter_property WRITE_ALLOWANCE EXPORT true
add_parameter TX_VDM_OFFSET STD_LOGIC_VECTOR 2000 ""
set_parameter_property TX_VDM_OFFSET DEFAULT_VALUE 2000
set_parameter_property TX_VDM_OFFSET DISPLAY_NAME TX_VDM_OFFSET
set_parameter_property TX_VDM_OFFSET WIDTH 32
set_parameter_property TX_VDM_OFFSET UNITS None
set_parameter_property TX_VDM_OFFSET DESCRIPTION ""
set_parameter_property TX_VDM_OFFSET AFFECTS_GENERATION false
set_parameter_property TX_VDM_OFFSET HDL_PARAMETER true
set_parameter_property TX_VDM_OFFSET EXPORT true
add_parameter RX_VDM_OFFSET STD_LOGIC_VECTOR 2000 ""
set_parameter_property RX_VDM_OFFSET DEFAULT_VALUE 2000
set_parameter_property RX_VDM_OFFSET DISPLAY_NAME RX_VDM_OFFSET
set_parameter_property RX_VDM_OFFSET WIDTH 32
set_parameter_property RX_VDM_OFFSET UNITS None
set_parameter_property RX_VDM_OFFSET DESCRIPTION ""
set_parameter_property RX_VDM_OFFSET AFFECTS_GENERATION false
set_parameter_property RX_VDM_OFFSET HDL_PARAMETER true
set_parameter_property RX_VDM_OFFSET EXPORT true
add_parameter PMCI_BASEADDR STD_LOGIC_VECTOR 20000 ""
set_parameter_property PMCI_BASEADDR DEFAULT_VALUE 20000
set_parameter_property PMCI_BASEADDR DISPLAY_NAME PMCI_BASEADDR
set_parameter_property PMCI_BASEADDR WIDTH 32
set_parameter_property PMCI_BASEADDR UNITS None
set_parameter_property PMCI_BASEADDR DESCRIPTION ""
set_parameter_property PMCI_BASEADDR AFFECTS_GENERATION false
set_parameter_property PMCI_BASEADDR HDL_PARAMETER true
set_parameter_property PMCI_BASEADDR EXPORT true
add_parameter FEAT_ID STD_LOGIC_VECTOR 0
set_parameter_property FEAT_ID DEFAULT_VALUE 20
set_parameter_property FEAT_ID DISPLAY_NAME FEAT_ID`
set_parameter_property FEAT_ID WIDTH 8
set_parameter_property FEAT_ID UNITS None
set_parameter_property FEAT_ID AFFECTS_GENERATION false
set_parameter_property FEAT_ID HDL_PARAMETER true
set_parameter_property FEAT_ID EXPORT true
add_parameter FEAT_VER STD_LOGIC_VECTOR 0
set_parameter_property FEAT_VER DEFAULT_VALUE 0
set_parameter_property FEAT_VER DISPLAY_NAME FEAT_VER
set_parameter_property FEAT_VER WIDTH 2
set_parameter_property FEAT_VER UNITS None
set_parameter_property FEAT_VER ALLOWED_RANGES 0:3
set_parameter_property FEAT_VER AFFECTS_GENERATION false
set_parameter_property FEAT_VER HDL_PARAMETER true
set_parameter_property FEAT_VER EXPORT true
add_parameter END_OF_LIST STD_LOGIC_VECTOR 0
set_parameter_property END_OF_LIST DEFAULT_VALUE 0
set_parameter_property END_OF_LIST DISPLAY_NAME END_OF_LIST
set_parameter_property END_OF_LIST WIDTH 2
set_parameter_property END_OF_LIST UNITS None
set_parameter_property END_OF_LIST ALLOWED_RANGES 0:3
set_parameter_property END_OF_LIST AFFECTS_GENERATION false
set_parameter_property END_OF_LIST HDL_PARAMETER true
set_parameter_property END_OF_LIST EXPORT true
add_parameter NEXT_DFH_OFFSET STD_LOGIC_VECTOR 10000 ""
set_parameter_property NEXT_DFH_OFFSET DEFAULT_VALUE 1000
set_parameter_property NEXT_DFH_OFFSET DISPLAY_NAME NEXT_DFH_OFFSET
set_parameter_property NEXT_DFH_OFFSET WIDTH 32
set_parameter_property NEXT_DFH_OFFSET UNITS None
set_parameter_property NEXT_DFH_OFFSET DESCRIPTION ""
set_parameter_property NEXT_DFH_OFFSET AFFECTS_GENERATION false
set_parameter_property NEXT_DFH_OFFSET HDL_PARAMETER true
set_parameter_property NEXT_DFH_OFFSET EXPORT true

# pcie_ss_axis_if parameters
add_parameter USER_W INTEGER 10
set_parameter_property USER_W DEFAULT_VALUE 10
set_parameter_property USER_W DISPLAY_NAME USER_W
set_parameter_property USER_W UNITS None
set_parameter_property USER_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property USER_W AFFECTS_GENERATION false
#set_parameter_property USER_W HDL_PARAMETER true
set_parameter_property USER_W EXPORT true

add_parameter DATA_W INTEGER 512
set_parameter_property DATA_W DEFAULT_VALUE 512
set_parameter_property DATA_W DISPLAY_NAME DATA_W
set_parameter_property DATA_W UNITS None
set_parameter_property DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_W AFFECTS_GENERATION false
#set_parameter_property DATA_W HDL_PARAMETER true
set_parameter_property DATA_W EXPORT true

# ofs_fim_axi_lite_if parameters
add_parameter AWADDR_WIDTH INTEGER 21 ""
set_parameter_property AWADDR_WIDTH DEFAULT_VALUE 21
set_parameter_property AWADDR_WIDTH DISPLAY_NAME AWADDR_WIDTH
set_parameter_property AWADDR_WIDTH UNITS None
set_parameter_property AWADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AWADDR_WIDTH DESCRIPTION ""
set_parameter_property AWADDR_WIDTH AFFECTS_GENERATION false
#set_parameter_property AWADDR_WIDTH HDL_PARAMETER true
set_parameter_property AWADDR_WIDTH EXPORT true

add_parameter WDATA_WIDTH INTEGER 64 ""
set_parameter_property WDATA_WIDTH DEFAULT_VALUE 64
set_parameter_property WDATA_WIDTH DISPLAY_NAME WDATA_WIDTH
set_parameter_property WDATA_WIDTH UNITS None
set_parameter_property WDATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WDATA_WIDTH DESCRIPTION ""
set_parameter_property WDATA_WIDTH AFFECTS_GENERATION false
#set_parameter_property WDATA_WIDTH HDL_PARAMETER true
set_parameter_property WDATA_WIDTH EXPORT true

add_parameter ARADDR_WIDTH INTEGER 21 ""
set_parameter_property ARADDR_WIDTH DEFAULT_VALUE 21
set_parameter_property ARADDR_WIDTH DISPLAY_NAME ARADDR_WIDTH
set_parameter_property ARADDR_WIDTH UNITS None
set_parameter_property ARADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ARADDR_WIDTH DESCRIPTION ""
set_parameter_property ARADDR_WIDTH AFFECTS_GENERATION false
#set_parameter_property ARADDR_WIDTH HDL_PARAMETER true
set_parameter_property ARADDR_WIDTH EXPORT true

add_parameter RDATA_WIDTH INTEGER 64 ""
set_parameter_property RDATA_WIDTH DEFAULT_VALUE 64
set_parameter_property RDATA_WIDTH DISPLAY_NAME RDATA_WIDTH
set_parameter_property RDATA_WIDTH UNITS None
set_parameter_property RDATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RDATA_WIDTH DESCRIPTION ""
set_parameter_property RDATA_WIDTH AFFECTS_GENERATION false
#set_parameter_property RDATA_WIDTH HDL_PARAMETER true
set_parameter_property RDATA_WIDTH EXPORT true


# 
# display items
# 

# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""
set_interface_property clk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clk clk clk Input 1

# 
# connection point rst_n
# 
add_interface rst_n reset end
set_interface_property rst_n associatedClock clk
set_interface_property rst_n synchronousEdges DEASSERT
set_interface_property rst_n ENABLED true
set_interface_property rst_n EXPORT_OF ""
set_interface_property rst_n PORT_NAME_MAP ""
set_interface_property rst_n CMSIS_SVD_VARIABLES ""
set_interface_property rst_n SVD_ADDRESS_GROUP ""
set_interface_property rst_n IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rst_n rst_n reset_n Input 1

# 
# connection point clk_csr
# 
add_interface clk_csr clock end
set_interface_property clk_csr ENABLED true
set_interface_property clk_csr EXPORT_OF ""
set_interface_property clk_csr PORT_NAME_MAP ""
set_interface_property clk_csr CMSIS_SVD_VARIABLES ""
set_interface_property clk_csr SVD_ADDRESS_GROUP ""
set_interface_property clk_csr IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clk_csr clk_csr clk Input 1

# 
# connection point rst_csr_n
# 
add_interface rst_csr_n reset end
set_interface_property rst_csr_n associatedClock clk
set_interface_property rst_csr_n synchronousEdges DEASSERT
set_interface_property rst_csr_n ENABLED true
set_interface_property rst_csr_n EXPORT_OF ""
set_interface_property rst_csr_n PORT_NAME_MAP ""
set_interface_property rst_csr_n CMSIS_SVD_VARIABLES ""
set_interface_property rst_csr_n SVD_ADDRESS_GROUP ""
set_interface_property rst_csr_n IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rst_csr_n rst_n_csr reset_n Input 1

# 
# connection point axis_rx_if
# 
add_interface axis_rx_if axi4stream end
set_interface_property axis_rx_if associatedClock clk
set_interface_property axis_rx_if associatedReset rst_n
set_interface_property axis_rx_if ENABLED true
set_interface_property axis_rx_if EXPORT_OF ""
set_interface_property axis_rx_if PORT_NAME_MAP ""
set_interface_property axis_rx_if CMSIS_SVD_VARIABLES ""
set_interface_property axis_rx_if SVD_ADDRESS_GROUP ""
set_interface_property axis_rx_if IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property axis_rx_if SV_INTERFACE_TYPE pcie_ss_axis_if
set_interface_property axis_rx_if SV_INTERFACE_MODPORT_TYPE sink

add_interface_port axis_rx_if axis_rx_if_tvalid tvalid Input 1
add_interface_port axis_rx_if axis_rx_if_tlast tlast Input 1
add_interface_port axis_rx_if axis_rx_if_tuser_vendor tuser Input USER_W
add_interface_port axis_rx_if axis_rx_if_tdata tdata Input DATA_W
add_interface_port axis_rx_if axis_rx_if_tkeep tkeep Input DATA_W/8
add_interface_port axis_rx_if axis_rx_if_tready tready Output 1

# 
# connection point axis_tx_if
# 
add_interface axis_tx_if axi4stream start
set_interface_property axis_tx_if associatedClock clk
set_interface_property axis_tx_if associatedReset rst_n
set_interface_property axis_tx_if ENABLED true
set_interface_property axis_tx_if EXPORT_OF ""
set_interface_property axis_tx_if PORT_NAME_MAP ""
set_interface_property axis_tx_if CMSIS_SVD_VARIABLES ""
set_interface_property axis_tx_if SVD_ADDRESS_GROUP ""
set_interface_property axis_tx_if IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property axis_tx_if SV_INTERFACE_TYPE pcie_ss_axis_if
set_interface_property axis_tx_if SV_INTERFACE_MODPORT_TYPE source

add_interface_port axis_tx_if axis_tx_if_tvalid tvalid Output 1
add_interface_port axis_tx_if axis_tx_if_tlast tlast Output 1
add_interface_port axis_tx_if axis_tx_if_tuser_vendor tuser Output USER_W
add_interface_port axis_tx_if axis_tx_if_tdata tdata Output DATA_W
add_interface_port axis_tx_if axis_tx_if_tkeep tkeep Output DATA_W/8
add_interface_port axis_tx_if axis_tx_if_tready tready Input 1

# 
# connection point axi_m_if
# 
add_interface axi_m_if axi4lite start
set_interface_property axi_m_if associatedClock clk
set_interface_property axi_m_if associatedReset rst_n
set_interface_property axi_m_if ENABLED true
set_interface_property axi_m_if EXPORT_OF ""
set_interface_property axi_m_if PORT_NAME_MAP ""
set_interface_property axi_m_if CMSIS_SVD_VARIABLES ""
set_interface_property axi_m_if SVD_ADDRESS_GROUP ""
set_interface_property axi_m_if IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property axi_m_if SV_INTERFACE_TYPE ofs_fim_axi_lite_if
#set_interface_property axi_m_if SV_INTERFACE_MODPORT_TYPE "master"

# Write address channel
add_interface_port axi_m_if axi_m_if_awready awready input 1
add_interface_port axi_m_if axi_m_if_awvalid awvalid output 1
add_interface_port axi_m_if axi_m_if_awaddr awaddr output AWADDR_WIDTH
add_interface_port axi_m_if axi_m_if_awprot awprot output 3
# Write data channel
add_interface_port axi_m_if axi_m_if_if_wready wready input 1
add_interface_port axi_m_if axi_m_if_wvalid wvalid output 1
add_interface_port axi_m_if axi_m_if_wdata wdata output WDATA_WIDTH
add_interface_port axi_m_if axi_m_if_wstrb wstrb output WDATA_WIDTH/8
# Write response channel
add_interface_port axi_m_if axi_m_if_bready bready output 1
add_interface_port axi_m_if axi_m_if_bvalid bvalid input 1
add_interface_port axi_m_if axi_m_if_bresp bresp input 2
# Read address channel
add_interface_port axi_m_if axi_m_if_arready arready input 1
add_interface_port axi_m_if axi_m_if_arvalid arvalid output 1
add_interface_port axi_m_if axi_m_if_araddr araddr output ARADDR_WIDTH
add_interface_port axi_m_if axi_m_if_arprot arprot output 3
# Read response channel
add_interface_port axi_m_if axi_m_if_rready rready output 1
add_interface_port axi_m_if axi_m_if_rvalid rvalid input 1
add_interface_port axi_m_if axi_m_if_rdata rdata input RDATA_WIDTH
add_interface_port axi_m_if axi_m_if_rresp rresp input 2



# 
# connection point axi_s_if
# 
add_interface axi_s_if axi4lite end
set_interface_property axi_s_if associatedClock clk
set_interface_property axi_s_if associatedReset rst_n
set_interface_property axi_s_if ENABLED true
set_interface_property axi_s_if EXPORT_OF ""
set_interface_property axi_s_if PORT_NAME_MAP ""
set_interface_property axi_s_if CMSIS_SVD_VARIABLES ""
set_interface_property axi_s_if SVD_ADDRESS_GROUP ""
set_interface_property axi_s_if IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property axi_s_if SV_INTERFACE_TYPE ofs_fim_axi_lite_if
#set_interface_property axi_s_if SV_INTERFACE_MODPORT_TYPE "slave"

# Write address channel
add_interface_port axi_s_if axi_s_if_awready awready output 1
add_interface_port axi_s_if axi_s_if_awvalid awvalid input 1
add_interface_port axi_s_if axi_s_if_awaddr awaddr input AWADDR_WIDTH
add_interface_port axi_s_if axi_s_if_awprot awprot input 3
# Write data channel
add_interface_port axi_s_if axi_s_if_wready wready output 1
add_interface_port axi_s_if axi_s_if_wvalid wvalid input 1
add_interface_port axi_s_if axi_s_if_wdata wdata input WDATA_WIDTH
add_interface_port axi_s_if axi_s_if_wstrb wstrb input WDATA_WIDTH/8
# Write response channel
add_interface_port axi_s_if axi_s_if_bready bready input 1
add_interface_port axi_s_if axi_s_if_bvalid bvalid output 1
add_interface_port axi_s_if axi_s_if_bresp bresp output 2
# Read address channel
add_interface_port axi_s_if axi_s_if_arready arready output 1
add_interface_port axi_s_if axi_s_if_arvalid arvalid input 1
add_interface_port axi_s_if axi_s_if_araddr araddr input ARADDR_WIDTH
add_interface_port axi_s_if axi_s_if_arprot arprot input 3
# Read response channel
add_interface_port axi_s_if axi_s_if_rready rready input 1
add_interface_port axi_s_if axi_s_if_rvalid rvalid output 1
add_interface_port axi_s_if axi_s_if_rdata rdata output RDATA_WIDTH
add_interface_port axi_s_if axi_s_if_rresp rresp output 2


# 
# connection point axi_m_pmci_vdm_if
# 
add_interface axi_m_pmci_vdm_if axi4lite start
set_interface_property axi_m_pmci_vdm_if associatedClock clk
set_interface_property axi_m_pmci_vdm_if associatedReset rst_n
set_interface_property axi_m_pmci_vdm_if ENABLED true
set_interface_property axi_m_pmci_vdm_if EXPORT_OF ""
set_interface_property axi_m_pmci_vdm_if PORT_NAME_MAP ""
set_interface_property axi_m_pmci_vdm_if CMSIS_SVD_VARIABLES ""
set_interface_property axi_m_pmci_vdm_if SVD_ADDRESS_GROUP ""
set_interface_property axi_m_pmci_vdm_if IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property axi_m_pmci_vdm_if SV_INTERFACE_TYPE ofs_fim_axi_lite_if
#set_interface_property axi_m_pmci_vdm_if SV_INTERFACE_MODPORT_TYPE "master"

# Write address channel
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_awready awready input 1
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_awvalid awvalid output 1
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_awaddr awaddr output AWADDR_WIDTH
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_awprot awprot output 3
# Write data channel
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_wready wready input 1
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_wvalid wvalid output 1
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_wdata wdata output WDATA_WIDTH
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_wstrb wstrb output WDATA_WIDTH/8
# Write response channel
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_bready bready output 1
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_bvalid bvalid input 1
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_bresp bresp input 2
# Read address channel
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_arready arready input 1
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_arvalid arvalid output 1
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_araddr araddr output ARADDR_WIDTH
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_arprot arprot output 3
# Read response channel
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_rready rready output 1
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_rvalid rvalid input 1
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_rdata rdata input RDATA_WIDTH
add_interface_port axi_m_pmci_vdm_if axi_m_pmci_vdm_if_rresp rresp input 2



# 
# connection point flr_rst_n
# 
add_interface flr_rst_n conduit end
set_interface_property flr_rst_n associatedClock clk 
set_interface_property flr_rst_n associatedReset rst_n
set_interface_property flr_rst_n ENABLED true
add_interface_port flr_rst_n flr_rst_n flr_rst_n Input 1


# 
# connection point flr_ack
# 
add_interface flr_ack conduit end
set_interface_property flr_ack associatedClock clk
set_interface_property flr_ack ENABLED true
add_interface_port flr_ack flr_ack flr_ack Output 1


