#!/bin/bash

# This script checks to see if clocks.sta.fail.summary is empty (meaning no clock domain failed timing)
# The clocks.sta.fail.summary is generated by report_timing.sh (This script will need to run after that)
# The intent is for this script to run in the build flow (with env variables set)


# Check if file exists. -s only checks if the file exist AND size > 0
if [ ! -e ${WORK_DIR}/syn/syn_top/output_files/timing_report/clocks.sta.fail.summary ]; then
    echo " Error: Cannot find ${WORK_DIR}/syn/syn_top/output_files/timing_report/clocks.sta.fail.summary" 1>&2
    exit 1
fi

# display work directory and artifact directory
echo ""
echo "Compile work directory:     ${WORK_DIR}/syn/syn_top"
echo "Compile artifact directory: ${WORK_DIR}/syn/syn_top/output_files"

echo ""

echo "***********************************"
echo "***"
echo "***        OFS_PROJECT: ${OFS_PROJECT}"
if [ "${OFS_FIM}" != "." ] && [ "${OFS_FIM}" != "" ]; then
    echo "***        OFS_FIM: ${OFS_FIM}"
fi
if [ "${OFS_BOARD}" != "." ] && [ "${OFS_BOARD}" != "" ]; then
    echo "***        OFS_BOARD: ${OFS_BOARD}"
fi
echo "***        Q_PROJECT:  ${Q_PROJECT}"
echo "***        Q_REVISION: ${Q_REVISION}"
echo "***        SEED: ${SEED}"
echo "***        Build Complete"

# clocks.sta.fail.summary filesize > 0 if timing failed (contains collection of failed clock domains)
if [ ! -s ${WORK_DIR}/syn/syn_top/output_files/timing_report/clocks.sta.fail.summary ]; then
    echo "***        Timing Passed!"
else
    echo "***        Timing FAILED!!!"
fi
echo "***"
echo "***********************************"

