#!/bin/bash
# Copyright (C) 2021-2022 Intel Corporation
# SPDX-License-Identifier: MIT

# This script checks to see if clocks.sta.fail.summary is empty (meaning no clock domain failed timing)
# The clocks.sta.fail.summary is generated by report_timing.sh (This script will need to run after that)
# The intent is for this script to run in the build flow (with env variables set)


# Check if file exists. -s only checks if the file exist AND size > 0
if [ ! -e ${WORK_SYN_TOP_PATH}/output_files/timing_report/clocks.sta.fail.summary ]; then
    echo " Warning: Cannot find ${WORK_SYN_TOP_PATH}/output_files/timing_report/clocks.sta.fail.summary" 1>&2
    exit 0
fi

# display work directory and artifact directory
echo ""
echo "Compile work directory:     ${WORK_SYN_TOP_PATH}"
echo "Compile artifact directory: ${WORK_SYN_TOP_PATH}/output_files"

echo ""

echo "***********************************"
echo "***"
echo "***        OFS_PROJECT: ${OFS_PROJECT}"
if [ "${OFS_FIM}" != "." ] && [ "${OFS_FIM}" != "" ]; then
    echo "***        OFS_FIM: ${OFS_FIM}"
fi
if [ "${OFS_BOARD}" != "." ] && [ "${OFS_BOARD}" != "" ]; then
    echo "***        OFS_BOARD: ${OFS_BOARD}"
fi
echo "***        Q_PROJECT:  ${Q_PROJECT}"
echo "***        Q_REVISION: ${Q_REVISION}"
echo "***        SEED: ${SEED}"
echo "***        Build Complete"

# clocks.sta.fail.summary filesize > 0 if timing failed (contains collection of failed clock domains)
if [ ! -s ${WORK_SYN_TOP_PATH}/output_files/timing_report/clocks.sta.fail.summary ]; then
    echo "***        Timing Passed!"
    retcode=0
else
    echo "***        Timing FAILED!!!"
    retcode=1
fi
echo "***"
echo "***********************************"

if [ "$REPORT_TIMING_FAILURE_AS_ERROR" == 1 ]; then
    exit $retcode
fi
