// Copyright 2020 Intel Corporation
// SPDX-License-Identifier: MIT

// Generated by one of Gregg's toys.   Share And Enjoy.
// Executable compiled Sep 14 2017 14:08:19
// This file was generated 08/05/2020 12:05:39

// This is a small one.  building it from simple LUTs

module prio_enc_w4_t1 #(
    parameter SIM_EMULATE = 1'b0
) (
    input clk,
    input [3:0] din,
    output [2:0] dout
);

wire [2:0] dout_w;
wire [5:0] din_6 = {2'b00, din};

////////////////////////////////
// all inputs -> output[0]


generate
    if (SIM_EMULATE) begin
        wire [63:0] local_mask = 64'h4544454545444545;
        wire [5:0] local_din = {din_6[5],din_6[4],din_6[3],din_6[2],din_6[1],din_6[0]};
        assign dout_w[0] = local_mask [local_din];
    end else begin
        //Note: the S5 cell is 99% the same, and compatible
        //stratixv_lcell_comb s5c (
 
        fourteennm_lcell_comb  #(
            .lut_mask(64'h4544454545444545),
            .shared_arith("off"),
            .extended_lut("off")
        ) s10c_0 (
            .dataa (din_6[0]),
            .datab (din_6[1]),
            .datac (din_6[2]),
            .datad (din_6[3]),
            .datae (din_6[4]),
            .dataf (din_6[5]),
            .datag(1'b1),
            
            .cin(1'b1),
            
            
            // synthesis translate_off
            // this is for stratix 10 (fourteen) but not the others
            .datah(1'b1),
                        
            // this does not exist in S10, but is partially there in the models right this second
            .sharein(1'b0),
            // synthesis translate_on
            
            .sumout(),.cout(),.shareout(),
            .combout(dout_w[0])
        );
    end
endgenerate

////////////////////////////////
// all inputs -> output[1]


generate
    if (SIM_EMULATE) begin
        wire [63:0] local_mask = 64'h1110111011101111;
        wire [5:0] local_din = {din_6[5],din_6[4],din_6[3],din_6[2],din_6[1],din_6[0]};
        assign dout_w[1] = local_mask [local_din];
    end else begin
        //Note: the S5 cell is 99% the same, and compatible
        //stratixv_lcell_comb s5c (
 
        fourteennm_lcell_comb  #(
            .lut_mask(64'h1110111011101111),
            .shared_arith("off"),
            .extended_lut("off")
        ) s10c_1 (
            .dataa (din_6[0]),
            .datab (din_6[1]),
            .datac (din_6[2]),
            .datad (din_6[3]),
            .datae (din_6[4]),
            .dataf (din_6[5]),
            .datag(1'b1),
            
            .cin(1'b1),
            
            
            // synthesis translate_off
            // this is for stratix 10 (fourteen) but not the others
            .datah(1'b1),
                        
            // this does not exist in S10, but is partially there in the models right this second
            .sharein(1'b0),
            // synthesis translate_on
            
            .sumout(),.cout(),.shareout(),
            .combout(dout_w[1])
        );
    end
endgenerate

////////////////////////////////
// all inputs -> output[2]


generate
    if (SIM_EMULATE) begin
        wire [63:0] local_mask = 64'h0001000100010001;
        wire [5:0] local_din = {din_6[5],din_6[4],din_6[3],din_6[2],din_6[1],din_6[0]};
        assign dout_w[2] = local_mask [local_din];
    end else begin
        //Note: the S5 cell is 99% the same, and compatible
        //stratixv_lcell_comb s5c (
 
        fourteennm_lcell_comb  #(
            .lut_mask(64'h0001000100010001),
            .shared_arith("off"),
            .extended_lut("off")
        ) s10c_2 (
            .dataa (din_6[0]),
            .datab (din_6[1]),
            .datac (din_6[2]),
            .datad (din_6[3]),
            .datae (din_6[4]),
            .dataf (din_6[5]),
            .datag(1'b1),
            
            .cin(1'b1),
            
            
            // synthesis translate_off
            // this is for stratix 10 (fourteen) but not the others
            .datah(1'b1),
                        
            // this does not exist in S10, but is partially there in the models right this second
            .sharein(1'b0),
            // synthesis translate_on
            
            .sumout(),.cout(),.shareout(),
            .combout(dout_w[2])
        );
    end
endgenerate

////////////////////////////////
// output latency is 1

reg [2:0] dout_r;
always @(posedge clk) dout_r <= dout_w;
assign dout = dout_r;

endmodule

