# TCL File Generated by Component Editor 22.1
# Fri Jul 15 10:40:34 PDT 2022
# DO NOT MODIFY


# 
# protocol_checker "protocol_checker" v1.0
#  2022.07.15.10:40:33
# 
# 

# 
# request TCL package from ACDS 22.1
# 
package require -exact qsys 22.1


# 
# module protocol_checker
# 
set_module_property DESCRIPTION ""
set_module_property NAME protocol_checker
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ofs infra"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME protocol_checker
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL afu_intf
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file afu_intf.sv SYSTEM_VERILOG PATH afu_intf.sv TOP_LEVEL_FILE
add_fileset_file mmio_handler.sv SYSTEM_VERILOG PATH mmio_handler.sv
add_fileset_file port_traffic_control.sv SYSTEM_VERILOG PATH port_traffic_control.sv
add_fileset_file port_tx_fifo.sv SYSTEM_VERILOG PATH port_tx_fifo.sv
add_fileset_file protocol_checker.sv SYSTEM_VERILOG PATH protocol_checker.sv
add_fileset_file protocol_checker_csr.sv SYSTEM_VERILOG PATH protocol_checker_csr.sv
add_fileset_file tx_filter.sv SYSTEM_VERILOG PATH tx_filter.sv

# 
# file sets
# 
add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL afu_intf
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file afu_intf.sv SYSTEM_VERILOG PATH afu_intf.sv TOP_LEVEL_FILE
add_fileset_file mmio_handler.sv SYSTEM_VERILOG PATH mmio_handler.sv
add_fileset_file port_traffic_control.sv SYSTEM_VERILOG PATH port_traffic_control.sv
add_fileset_file port_tx_fifo.sv SYSTEM_VERILOG PATH port_tx_fifo.sv
add_fileset_file protocol_checker.sv SYSTEM_VERILOG PATH protocol_checker.sv
add_fileset_file protocol_checker_csr.sv SYSTEM_VERILOG PATH protocol_checker_csr.sv
add_fileset_file tx_filter.sv SYSTEM_VERILOG PATH tx_filter.sv

# pcie_ss_axis_if parameters
add_parameter USER_W INTEGER 10
set_parameter_property USER_W DEFAULT_VALUE 10
set_parameter_property USER_W DISPLAY_NAME USER_W
set_parameter_property USER_W UNITS None
set_parameter_property USER_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property USER_W AFFECTS_GENERATION false
set_parameter_property USER_W EXPORT true

add_parameter DATA_W INTEGER 512
set_parameter_property DATA_W DEFAULT_VALUE 512
set_parameter_property DATA_W DISPLAY_NAME DATA_W
set_parameter_property DATA_W UNITS None
set_parameter_property DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_W AFFECTS_GENERATION false
set_parameter_property DATA_W HDL_PARAMETER true
set_parameter_property DATA_W EXPORT true

# ofs_fim_axi_lite_if parameters
add_parameter AWADDR_WIDTH INTEGER 21 ""
set_parameter_property AWADDR_WIDTH DEFAULT_VALUE 21
set_parameter_property AWADDR_WIDTH DISPLAY_NAME AWADDR_WIDTH
set_parameter_property AWADDR_WIDTH UNITS None
set_parameter_property AWADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AWADDR_WIDTH DESCRIPTION ""
set_parameter_property AWADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property AWADDR_WIDTH EXPORT true

add_parameter WDATA_WIDTH INTEGER 64 ""
set_parameter_property WDATA_WIDTH DEFAULT_VALUE 64
set_parameter_property WDATA_WIDTH DISPLAY_NAME WDATA_WIDTH
set_parameter_property WDATA_WIDTH UNITS None
set_parameter_property WDATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WDATA_WIDTH DESCRIPTION ""
set_parameter_property WDATA_WIDTH AFFECTS_GENERATION false
set_parameter_property WDATA_WIDTH EXPORT true

add_parameter ARADDR_WIDTH INTEGER 21 ""
set_parameter_property ARADDR_WIDTH DEFAULT_VALUE 21
set_parameter_property ARADDR_WIDTH DISPLAY_NAME ARADDR_WIDTH
set_parameter_property ARADDR_WIDTH UNITS None
set_parameter_property ARADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ARADDR_WIDTH DESCRIPTION ""
set_parameter_property ARADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property ARADDR_WIDTH EXPORT true

add_parameter RDATA_WIDTH INTEGER 64 ""
set_parameter_property RDATA_WIDTH DEFAULT_VALUE 64
set_parameter_property RDATA_WIDTH DISPLAY_NAME RDATA_WIDTH
set_parameter_property RDATA_WIDTH UNITS None
set_parameter_property RDATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RDATA_WIDTH DESCRIPTION ""
set_parameter_property RDATA_WIDTH AFFECTS_GENERATION false
set_parameter_property RDATA_WIDTH EXPORT true

# 
# display items
# 

# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""
set_interface_property clk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clk clk clk Input 1

# 
# connection point rst_n
# 
add_interface rst_n reset end
set_interface_property rst_n associatedClock clk
set_interface_property rst_n synchronousEdges DEASSERT
set_interface_property rst_n ENABLED true
set_interface_property rst_n EXPORT_OF ""
set_interface_property rst_n PORT_NAME_MAP ""
set_interface_property rst_n CMSIS_SVD_VARIABLES ""
set_interface_property rst_n SVD_ADDRESS_GROUP ""
set_interface_property rst_n IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rst_n rst_n reset_n Input 1

# 
# connection point clk_csr
# 
add_interface clk_csr clock end
set_interface_property clk_csr ENABLED true
set_interface_property clk_csr EXPORT_OF ""
set_interface_property clk_csr PORT_NAME_MAP ""
set_interface_property clk_csr CMSIS_SVD_VARIABLES ""
set_interface_property clk_csr SVD_ADDRESS_GROUP ""
set_interface_property clk_csr IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clk_csr clk_csr clk Input 1

# 
# connection point rst_csr_n
# 
add_interface rst_csr_n reset end
set_interface_property rst_csr_n associatedClock clk
set_interface_property rst_csr_n synchronousEdges DEASSERT
set_interface_property rst_csr_n ENABLED true
set_interface_property rst_csr_n EXPORT_OF ""
set_interface_property rst_csr_n PORT_NAME_MAP ""
set_interface_property rst_csr_n CMSIS_SVD_VARIABLES ""
set_interface_property rst_csr_n SVD_ADDRESS_GROUP ""
set_interface_property rst_csr_n IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rst_csr_n rst_n_csr reset_n Input 1

# 
# connection point pwr_good_csr_clk_n
# 
add_interface pwr_good_csr_clk_n conduit end
set_interface_property pwr_good_csr_clk_n associatedClock clock
set_interface_property pwr_good_csr_clk_n ENABLED true

add_interface_port pwr_good_csr_clk_n pwr_good_csr_clk_n pwr_good_csr_clk_n Input 1

# 
# connection point i_afu_softreset
# 
add_interface i_afu_softreset conduit end
set_interface_property i_afu_softreset associatedClock clock
set_interface_property i_afu_softreset ENABLED true

add_interface_port i_afu_softreset i_afu_softreset i_afu_softreset Input 1

# 
# connection point o_sel_mmio_rsp
# 
add_interface o_sel_mmio_rsp conduit end
set_interface_property o_sel_mmio_rsp associatedClock clock
set_interface_property o_sel_mmio_rsp ENABLED true
add_interface_port o_sel_mmio_rsp o_sel_mmio_rsp o_sel_mmio_rsp Output 1

# 
# connection point o_read_flush_done
# 
add_interface o_read_flush_done conduit end
set_interface_property o_read_flush_done associatedClock clock
set_interface_property o_read_flush_done ENABLED true
add_interface_port o_read_flush_done o_read_flush_done o_read_flush_done Output 1

# 
# connection point h2a_axis_rx
# 
add_interface h2a_axis_rx axi4stream end
set_interface_property h2a_axis_rx associatedClock clk
set_interface_property h2a_axis_rx associatedReset rst_n
set_interface_property h2a_axis_rx ENABLED true
set_interface_property h2a_axis_rx EXPORT_OF ""
set_interface_property h2a_axis_rx PORT_NAME_MAP ""
set_interface_property h2a_axis_rx CMSIS_SVD_VARIABLES ""
set_interface_property h2a_axis_rx SVD_ADDRESS_GROUP ""
set_interface_property h2a_axis_rx IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property h2a_axis_rx SV_INTERFACE_TYPE pcie_ss_axis_if
set_interface_property h2a_axis_rx SV_INTERFACE_MODPORT_TYPE sink

add_interface_port h2a_axis_rx h2a_axis_rx_tvalid tvalid Input 1
add_interface_port h2a_axis_rx h2a_axis_rx_tlast tlast Input 1
add_interface_port h2a_axis_rx h2a_axis_rx_tuser_vendor tuser Input USER_W
add_interface_port h2a_axis_rx h2a_axis_rx_tdata tdata Input DATA_W
add_interface_port h2a_axis_rx h2a_axis_rx_tkeep tkeep Input DATA_W/8
add_interface_port h2a_axis_rx h2a_axis_rx_tready tready Output 1

# 
# connection point a2h_axis_tx
# 
add_interface a2h_axis_tx axi4stream start
set_interface_property a2h_axis_tx associatedClock clk
set_interface_property a2h_axis_tx associatedReset rst_n
set_interface_property a2h_axis_tx ENABLED true
set_interface_property a2h_axis_tx EXPORT_OF ""
set_interface_property a2h_axis_tx PORT_NAME_MAP ""
set_interface_property a2h_axis_tx CMSIS_SVD_VARIABLES ""
set_interface_property a2h_axis_tx SVD_ADDRESS_GROUP ""
set_interface_property a2h_axis_tx IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property a2h_axis_tx SV_INTERFACE_TYPE pcie_ss_axis_if
set_interface_property a2h_axis_tx SV_INTERFACE_MODPORT_TYPE source

add_interface_port a2h_axis_tx a2h_axis_tx_tvalid tvalid Output 1
add_interface_port a2h_axis_tx a2h_axis_tx_tlast tlast Output 1
add_interface_port a2h_axis_tx a2h_axis_tx_tuser_vendor tuser Output USER_W
add_interface_port a2h_axis_tx a2h_axis_tx_tdata tdata Output DATA_W
add_interface_port a2h_axis_tx a2h_axis_tx_tkeep tkeep Output DATA_W/8
add_interface_port a2h_axis_tx a2h_axis_tx_tready tready Input 1

# 
# connection point afu_axis_rx
# 
add_interface afu_axis_rx axi4stream start
set_interface_property afu_axis_rx associatedClock clk
set_interface_property afu_axis_rx associatedReset rst_n
set_interface_property afu_axis_rx ENABLED true
set_interface_property afu_axis_rx EXPORT_OF ""
set_interface_property afu_axis_rx PORT_NAME_MAP ""
set_interface_property afu_axis_rx CMSIS_SVD_VARIABLES ""
set_interface_property afu_axis_rx SVD_ADDRESS_GROUP ""
set_interface_property afu_axis_rx IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property afu_axis_rx SV_INTERFACE_TYPE pcie_ss_axis_if
set_interface_property afu_axis_rx SV_INTERFACE_MODPORT_TYPE source

add_interface_port afu_axis_rx afu_axis_rx_tvalid tvalid Output 1
add_interface_port afu_axis_rx afu_axis_rx_tlast tlast Output 1
add_interface_port afu_axis_rx afu_axis_rx_tuser_vendor tuser Output USER_W
add_interface_port afu_axis_rx afu_axis_rx_tdata tdata Output DATA_W
add_interface_port afu_axis_rx afu_axis_rx_tkeep tkeep Output DATA_W/8
add_interface_port afu_axis_rx afu_axis_rx_tready tready Input 1


# 
# connection point afu_axis_tx
# 
add_interface afu_axis_tx axi4stream end
set_interface_property afu_axis_tx associatedClock clk
set_interface_property afu_axis_tx associatedReset rst_n
set_interface_property afu_axis_tx ENABLED true
set_interface_property afu_axis_tx EXPORT_OF ""
set_interface_property afu_axis_tx PORT_NAME_MAP ""
set_interface_property afu_axis_tx CMSIS_SVD_VARIABLES ""
set_interface_property afu_axis_tx SVD_ADDRESS_GROUP ""
set_interface_property afu_axis_tx IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property afu_axis_tx SV_INTERFACE_TYPE pcie_ss_axis_if
set_interface_property afu_axis_tx SV_INTERFACE_MODPORT_TYPE sink

add_interface_port afu_axis_tx afu_axis_tx_tvalid tvalid Input 1
add_interface_port afu_axis_tx afu_axis_tx_tlast tlast Input 1
add_interface_port afu_axis_tx afu_axis_tx_tuser_vendor tuser Input USER_W
add_interface_port afu_axis_tx afu_axis_tx_tdata tdata Input DATA_W
add_interface_port afu_axis_tx afu_axis_tx_tkeep tkeep Input DATA_W/8
add_interface_port afu_axis_tx afu_axis_tx_tready tready Output 1

# 
# connection point csr_if
# 
add_interface csr_if axi4lite end
set_interface_property csr_if associatedClock clk
set_interface_property csr_if associatedReset rst_n
set_interface_property csr_if ENABLED true
set_interface_property csr_if EXPORT_OF ""
set_interface_property csr_if PORT_NAME_MAP ""
set_interface_property csr_if CMSIS_SVD_VARIABLES ""
set_interface_property csr_if SVD_ADDRESS_GROUP ""
set_interface_property csr_if IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property csr_if SV_INTERFACE_TYPE ofs_fim_axi_lite_if
#set_interface_property csr_if SV_INTERFACE_MODPORT_TYPE "slave"

# Write address channel
add_interface_port csr_if csr_if_awready awready output 1
add_interface_port csr_if csr_if_awvalid awvalid input 1
add_interface_port csr_if csr_if_awaddr awaddr input AWADDR_WIDTH
add_interface_port csr_if csr_if_awprot awprot input 3
# Write data channel
add_interface_port csr_if csr_if_wready wready output 1
add_interface_port csr_if csr_if_wvalid wvalid input 1
add_interface_port csr_if csr_if_wdata wdata input WDATA_WIDTH
add_interface_port csr_if csr_if_wstrb wstrb input WDATA_WIDTH/8
# Write response channel
add_interface_port csr_if csr_if_bready bready input 1
add_interface_port csr_if csr_if_bvalid bvalid output 1
add_interface_port csr_if csr_if_bresp bresp output 2
# Read address channel
add_interface_port csr_if csr_if_arready arready output 1
add_interface_port csr_if csr_if_arvalid arvalid input 1
add_interface_port csr_if csr_if_araddr araddr input ARADDR_WIDTH
add_interface_port csr_if csr_if_arprot arprot input 3
# Read response channel
add_interface_port csr_if csr_if_rready rready input 1
add_interface_port csr_if csr_if_rvalid rvalid output 1
add_interface_port csr_if csr_if_rdata rdata output RDATA_WIDTH
add_interface_port csr_if csr_if_rresp rresp output 2

# 
# parameters
# 
add_parameter ENABLE INTEGER 1
set_parameter_property ENABLE DEFAULT_VALUE 1
set_parameter_property ENABLE DISPLAY_NAME ENABLE
set_parameter_property ENABLE UNITS None
set_parameter_property ENABLE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE AFFECTS_GENERATION false
set_parameter_property ENABLE HDL_PARAMETER true
set_parameter_property ENABLE EXPORT true
add_parameter ENABLE_TAG_OCCUPIED_CHECK INTEGER 0
set_parameter_property ENABLE_TAG_OCCUPIED_CHECK DEFAULT_VALUE 0
set_parameter_property ENABLE_TAG_OCCUPIED_CHECK DISPLAY_NAME ENABLE_TAG_OCCUPIED_CHECK
set_parameter_property ENABLE_TAG_OCCUPIED_CHECK UNITS None
set_parameter_property ENABLE_TAG_OCCUPIED_CHECK ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ENABLE_TAG_OCCUPIED_CHECK AFFECTS_GENERATION false
set_parameter_property ENABLE_TAG_OCCUPIED_CHECK HDL_PARAMETER true
set_parameter_property ENABLE_TAG_OCCUPIED_CHECK EXPORT true
add_parameter FMTTYPE_W INTEGER 8
set_parameter_property FMTTYPE_W DEFAULT_VALUE 8
set_parameter_property FMTTYPE_W DISPLAY_NAME FMTTYPE_W
set_parameter_property FMTTYPE_W UNITS None
set_parameter_property FMTTYPE_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FMTTYPE_W AFFECTS_GENERATION false
set_parameter_property FMTTYPE_W HDL_PARAMETER true
set_parameter_property FMTTYPE_W EXPORT true
add_parameter LEN_W INTEGER 24
set_parameter_property LEN_W DEFAULT_VALUE 24
set_parameter_property LEN_W DISPLAY_NAME LEN_W
set_parameter_property LEN_W UNITS None
set_parameter_property LEN_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LEN_W AFFECTS_GENERATION false
set_parameter_property LEN_W HDL_PARAMETER true
set_parameter_property LEN_W EXPORT true
add_parameter TAG_W INTEGER 10
set_parameter_property TAG_W DEFAULT_VALUE 10
set_parameter_property TAG_W DISPLAY_NAME TAG_W
set_parameter_property TAG_W UNITS None
set_parameter_property TAG_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property TAG_W AFFECTS_GENERATION false
set_parameter_property TAG_W HDL_PARAMETER true
set_parameter_property TAG_W EXPORT true
add_parameter ADDR_W INTEGER 64
set_parameter_property ADDR_W DEFAULT_VALUE 64
set_parameter_property ADDR_W DISPLAY_NAME ADDR_W
set_parameter_property ADDR_W UNITS None
set_parameter_property ADDR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_W AFFECTS_GENERATION false
set_parameter_property ADDR_W HDL_PARAMETER true
set_parameter_property ADDR_W EXPORT true
add_parameter PCIE_EP_MAX_TAGS INTEGER 96
set_parameter_property PCIE_EP_MAX_TAGS DEFAULT_VALUE 96
set_parameter_property PCIE_EP_MAX_TAGS DISPLAY_NAME PCIE_EP_MAX_TAGS
set_parameter_property PCIE_EP_MAX_TAGS UNITS None
set_parameter_property PCIE_EP_MAX_TAGS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PCIE_EP_MAX_TAGS AFFECTS_GENERATION false
set_parameter_property PCIE_EP_MAX_TAGS HDL_PARAMETER true
set_parameter_property PCIE_EP_MAX_TAGS EXPORT true
add_parameter MAX_PLD_SIZE INTEGER 512
set_parameter_property MAX_PLD_SIZE DEFAULT_VALUE 512
set_parameter_property MAX_PLD_SIZE DISPLAY_NAME MAX_PLD_SIZE
set_parameter_property MAX_PLD_SIZE UNITS None
set_parameter_property MAX_PLD_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_PLD_SIZE AFFECTS_GENERATION false
set_parameter_property MAX_PLD_SIZE HDL_PARAMETER true
set_parameter_property MAX_PLD_SIZE EXPORT true
add_parameter MAX_RD_REQ_SIZE INTEGER 512
set_parameter_property MAX_RD_REQ_SIZE DEFAULT_VALUE 512
set_parameter_property MAX_RD_REQ_SIZE DISPLAY_NAME MAX_RD_REQ_SIZE
set_parameter_property MAX_RD_REQ_SIZE UNITS None
set_parameter_property MAX_RD_REQ_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_RD_REQ_SIZE AFFECTS_GENERATION false
set_parameter_property MAX_RD_REQ_SIZE HDL_PARAMETER true
set_parameter_property MAX_RD_REQ_SIZE EXPORT true

