// Copyright 2001-2023 Intel Corporation
// SPDX-License-Identifier: MIT




`timescale 1ps/1ps

// DESCRIPTION
// 1 input XOR gate.  Latency 0.
// Generated by one of Gregg's toys.   Share And Enjoy.

// HN edited:  Modified for internal use
module alt_e2550_xor1t0_hn (
    input [0:0] din,
    output dout
);

   
alt_e2550_lut6_hn #(.MASK(64'h6996966996696996) ) t0 (.din({1'b0,1'b0,1'b0,1'b0,1'b0,din}),.dout(dout));
//defparam t0 .SIM_EMULATE = SIM_EMULATE;
//defparam t0 .MASK = 64'h6996966996696996;

   //assign dout = din;
   
endmodule

