# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: MIT

#--------------------
#HE_HSSI Filelist
#--------------------
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/lib/bridges/axis_rx_mmio_bridge.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/lib/bridges/axis_tx_mmio_bridge.sv

set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/he_hssi_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/common/eth_rx_axis_cdc_fifo.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/common/eth_traffic_csr_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/common/ofs_fim_eth_f_traffic_controller_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/top_direct_green_bs/eth_traffic_pcie_tlp_to_csr.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/top_direct_green_bs/pcie_tlp_to_csr_no_dma.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/common/eth_traffic_csr.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/common/multi_port_axi_mac_seg_traffic_ctrl.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/common/multi_port_axi_sop_traffic_ctrl.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/common/multi_port_traffic_ctrl.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/common/pulse_sync.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/common/traffic_controller_wrapper.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/avalon_st_loopback.sv
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/avalon_st_loopback_csr.v
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/avalon_st_gen.v 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/avalon_st_loopback.sv 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/avalon_st_loopback_csr.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/avalon_st_mon.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/avalon_st_prtmux.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/eth_std_traffic_controller_top.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/shiftreg_ctrl.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/shiftreg_data.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/avalon_st_to_crc_if_bridge.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/bit_endian_converter.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/byte_endian_converter.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc_checksum_aligner.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc_comparator.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_calculator.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_chk.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_gen.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_lib/crc_ethernet.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_lib/crc_register.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_lib/crc32_dat8.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_lib/crc32_dat16.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_lib/crc32_dat24.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_lib/crc32_dat32.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_lib/crc32_dat32_any_byte.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_lib/crc32_dat40.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_lib/crc32_dat48.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_lib/crc32_dat56.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_lib/crc32_dat64.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_lib/crc32_dat64_any_byte.v 
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/eth_traffic_controller/crc32/crc32_lib/xor6.v

set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_100g/alt_aeuex_pkt_gen_sync.v
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_100g/alt_e100s10_data_block_buffer.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_100g/alt_e100s10_data_synchronizer.sv 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_100g/alt_e100s10_frame_buffer.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_100g/alt_e100s10_loopback_client.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_100g/alt_e100s10_pointer_synchronizer.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_100g/alt_e100s10_ready_skid.sv
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_100g/alt_aeuex_packet_client_tx.v 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_100g/alt_e100s10_packet_client.sv
set_global_assignment -name IP_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/lib/fifo/sc_fifo_tx_sc_fifo.ip

set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_f_packet_client_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_f_ed_avst2axi_bridge.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_f_ed_axis2avst_bridge.sv
#set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_f_packet_client_top_25G.sv
#set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_f_packet_client_top_50G.sv
#set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_f_packet_client_top_100G_1.sv
#set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_f_packet_client_top_100G_2.sv
#set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_f_packet_client_top_100G_4.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_f_packet_client_top_200G_2.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_f_packet_client_top_200G_4.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_f_packet_client_top_400G_4.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_f_packet_client_top_400G_8.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_100g_f_hw_ip_avmm_decoder.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_200g_f_hw_ip_avmm_decoder.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_400g_f_hw_ip_avmm_decoder.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_hw_avmm_decoder.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_hw_ip_avmm_decoder.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/ed_avst_to_axist_rx_mac_seg_if.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/ed_axist_to_avst_tx_mac_seg_if.sv

set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_multi_stream_rx_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/hssi_ss_multi_stream_tx_top.sv



set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_pkt_gen_rom.sv 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_pkt_gen_pingpong_bf.sv 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_pkt_gen_top.sv 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_hw_dual_clock_fifo.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_hw_dual_port_sram.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_hw_pointer_synchronizer.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_loopback_fifo.sv 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_loopback_client.sv 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_packet_client_ptp_monitor.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_packet_client_csr.sv 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_packet_client_csr_pkt_cnt.sv 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_packet_client_tx_mux.sv 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_packet_client_tx_interface.sv 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_packet_client_top.sv 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_pkt_stat_counter.sv 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_pkt_gen_ready_skid.sv 
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_latency_measure.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/gdr_pkt_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/pcs_packet_client.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/packet_client_csr.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/exd_std_synchronizer.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/counters.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/tx_packet_client.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/tmem.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/gen_pkt_mem_wrap.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/mem_wrapper.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/nbq_scsdpram.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/tscr.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/tmii.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/fifo_ff_12dp.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/tpcs.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/pipe.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/fifo_ff_8dp.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/tpgn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/fcs_pkt.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/crc_32.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/encoder.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/scramble_new.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_scram64_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_scram128_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_scram256_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor14t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor13t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor12t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor11t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor10t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor9t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor8t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor7t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor6t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor6t0_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor5t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor5t0_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor4t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor4t0_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor3t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor3t0_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor2t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor2t0_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor1t1_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_xor1t0_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/rx_packet_client.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/rmii.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/rchk.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/crc_32_chker.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/fifo_lat_0.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/rscr.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/decoder.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/descramble_new.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_descram64_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_descram128_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_descram256_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_e2550_lut6_hn.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/scrambler.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/scramble_c49.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/mem_ram.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/fifo_pref.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_packet_client_interface.sv
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_data_synchronizer.sv
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/altera_std_syncronizer.v
set_global_assignment -name SYSTEMVERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/avmm2axiLite_bridge.sv
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/alt_reset_delay.v
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_reset_synchronizer.v
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_altera_std_synchronizer_nocut.v
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_xcvr_resync_std.sv
set_global_assignment -name VERILOG_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_multibit_sync.v

set_global_assignment -name HEX_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/init_file_ctrl.200G.hex
set_global_assignment -name HEX_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/init_file_ctrl.400G.hex
set_global_assignment -name HEX_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/init_file_data.200G.hex
set_global_assignment -name HEX_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/init_file_data.400G.hex
set_global_assignment -name HEX_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_hw_pkt_gen_rom_init.200G_SEG.hex
set_global_assignment -name HEX_FILE $::env(BUILD_ROOT_REL)/ofs-common/src/common/he_hssi/pkt_client_mac_seg/eth_f_hw_pkt_gen_rom_init.400G_SEG.hex
