##
## Import all pcie_shims sources for simulation.
##

pcie_dm_req_splitter/ofs_fim_pcie_dm_cpl_merge.sv
pcie_dm_req_splitter/ofs_fim_pcie_dm_req_splitter.sv
pcie_dm_req_splitter/ofs_fim_pcie_dm_rx_rd_splitter.sv
pcie_dm_req_splitter/ofs_fim_pcie_dm_tx_req_splitter.sv
pcie_dm_req_splitter/ofs_fim_pcie_dm_tx_rdwr_req_splitter.sv
pcie_dm_req_splitter/ofs_fim_rotate_words_comb.sv

pcie_hdr_out_of_band/ofs_fim_pcie_hdr_extract.sv
pcie_hdr_out_of_band/ofs_fim_pcie_hdr_merge.sv
